# app.yaml
runtime: python39

# Aggiungi questa sezione per gestire lo scaling e risolvere il warning
automatic_scaling:
  max_instances: 2 # Inizia con un numero basso per controllare i costi

handlers:
# Gestisce tutti i file nella cartella frontend
- url: /(.*)
  static_files: frontend/\1
  upload: frontend/(.*)

# Rotta principale che serve index.html quando si visita l'URL base
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html